# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: '5.x'
    performMultiLevelLookup: true
    includePreviewVersions: true

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install --force'
    workingDir: "webstep/webstep/ClientApp"
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install react-bootstrap bootstrap styled-components material-ui-popup-state@^1.9.3 typescript @faker-js/faker react-pro-sidebar@0.7.1 react-router-dom @apollo/client @mui/material @mui/icons-material @mui/x-data-grid apollo react-chartjs-2 react-dom chart.js formik graphql react react-scripts react-toastify yup'
    workingDir: "webstep/webstep/ClientApp"
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: 'webstep/webstep/webstep.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True